export const POKEMON_NAME_COLUMN_WIDTH = 35;
export const POKEMON_TYPES_COLUMN_WIDTH = 25;
export const POKEMON_ATTACK_COLUMN_WIDTH = 9;
export const POKEMON_SP_ATTACK_COLUMN_WIDTH = 13;
export const POKEMON_DEFENSE_COLUMN_WIDTH = 9;
export const POKEMON_SP_DEFENSE_COLUMN_WIDTH = 11;
export const POKEMON_SPEED_COLUMN_WIDTH = 9;
export const POKEMON_HP_COLUMN_WIDTH = 10;
